gyroidos/gyroidos

Jenkinsfile
This commit catches errors due to attempts to access
non-existing variables such as CHANGE_TARGET in non-PR builds.
=>  Jenkinsfile: Fix mirror sync check

Jenkinsfile
This commit adapts the Jenkinsfile such that env.CHANGE_TARGET and env.PR_BRANCHES is checked to avoid exceptions due to properties not set by Jenkins.
=> Jenkinsfile: Check env in mirror sync

Jenkinsfile
For arm builds where the image is copied to sd cards with smaller sizes and low speed, the 10GB were a problem. Thus, we reduce this to 3GB which allows enough space for our pipeline tests and also allow smaller target sd cards.
=> Jenkinsfile: Reduced extra space from 10 GB to 3GB

Jenkinsfile
Added the kernel tarball in cml_updates folder to artifacts. This allows quick download of cml updates only without the need to download and extract the whole 'trustmeimage.img'.
=> Jenkinsfile: archive cml_updates kernel tarball

Jenkinsfile
With the new pipeline model 10 kept builds are sometimes too few as they are discarded quickly with many PRs. Let's try with 25.
=> Jenkinsfile: increase number of kept builds

Jenkinsfile
Since the main ogig was moved from cml repository to this one. The CHANGE_TARGET is not set for PRs in other repos. Thus, if building several PRs to, e.g., the cml repo, SSH ports during parallel integration tests could have been clashed. Using the BUILD_NUMBER from this repo should avoid that.
=> Jenkinsfile: Avoid ssh port clashes when building PRs simultaneously

Dockerfile, Jenkinsfile
This PR adapts the' Intgration Test' stage s.t. it is executed in a container to avoid name and port clashes during concurrent builds. Also, proper user initialization for the build user is done as in the Dockerfile in the gyroidos_build repo at yocto/docker/Dockerfile
=> Run integration tests in container + proper user initialization

Jenkinsfile
This commit fixes the Jenkinsfile s.t. CML logs are properly stored in the build Jenkins build artifacts for the integration tests with schsm support.
=> Jenkinsfile: Store CML logs after token test

Dockerfile, Jenkinsfile
This PR migrates CI scripts and related stages from the gyroidos/cml
repository, adds necessary dependencies to the Dockerfile and adapts
script paths as required due to https://github.com/gyroidos/cml/pull/441 and
https://github.com/gyroidos/meta-trustx/pull/217.
Also, the VNC port is now exposed through the Docker -p option.
=>  Move CI stages + scripts from gyroidos/cml, Expose VNC port during integration tests

Jenkinsfile
This PR modifies the Jenkinsfile s.t. builds of branches (not PRs) are supported again.
=> Jenkinsfile: Fix for branch builds

Dockerfile
This commit adds libcap-dev to the Dockerfile as sys/capability.h is required for the CML build since gyroidos/cml#443
=> Dockerfile: Add libcap-dev

Jenkinsfile
For guestos update tests we need a little more space on '/data/cml/operatingsystems', thus increase extra space on overall image.
=> Jenkinsfile: Increase extra space of image

Jenkinsfile
This commit re-introduces the lock for schsm tests.
=> Jenkinsfile: Introduce lock for schsm tests

Jenkinsfile
This commit adds the checkoutToSubdirectory option such that Jenkins places the manifest repository into the .manifests directory.
=> Jenkinsfile: Re-add checkoutToSubdirectory

Jenkinsfile
This PR enables an additional image to be built with ASAN enabled. To this end, meta-tmedbg is cloned and activated.
Requires meta-trustx:pr-204 and gyroidos_build:pr-109.
=> Jenkinsfile: Add image build with ASAN

Jenkinsfile, gyroidos-base.xml, yocto-arm64-tqma8mpxl.xml, yocto-raspberrypi.xml, yocto-toradex.xml, yocto-x86-genericx86-64.xml
On github the upstream repos where change from old codename trustx to project name gyroidos. Thus all meta-trustx* repos are named meta-gyroidos*. We changed this in all the manifests and Jenkinsfile, too.
=> tree-wide: renamed repos meta-trustx* to meta-gyroidos*

Jenkinsfile
Remove the lock for integration tests that is moved to the shared library in gyroidos/gyroidos_ci_common#33.
=> vars/Jenkinsfile: Remove lock for token tests

Jenkinsfile
Add options to the pipeline that allow keeping a build forever and setting the display name from upstream jobs.
=> Jenkinsfile: Add options to set display name and keep forever

yocto-riscv-beaglev-fire.xml
Rolling head polarfire layer dropped support for kirstone. Pin to 2024.09 until we move to scarthgap.
=> yocto-riscv-beaglev-fire: Pin polarfire bsp revision

Jenkinsfile
Remove the default value for SET_DISPLAY_NAME s.t. the build name is left untouched if no name is explicitly provided.
=> Jenkinsfile: Remove default for SET_DISPLAY_NAME

Dockerfile
Switch base image to Debian Trixie. Also, remove backport of OpenSSL version 3.3 as we support the OpenSSL version shipped by Trixie.
=> Dockerfile: Switch to Debian Trixie
